#!/bin/bash
# Test COSP

# Download and check COSP github code
./check_cosp_github.sh

# Run the COSP driver
cosp_driver cosp_input_um_2d.nc > output.txt

# Test output against KGO
ierr=0

(diff -q output.txt ifort_17_0_7.txt && \
 echo 'Matched ifort 17.0.7 output') || \
(diff -q output.txt gfortran_8_1_0.txt && \
 echo 'Matched gfortran 8.1.0 output') || ierr=1

if [ $ierr -gt 0 ] ; then
  exit 1
else
  rm -f output.txt
  rm -f cosp_input_um_2d.nc
  rm -f cosp_out.nc
  echo OK
  exit 0
fi
