# AGNI configuration file 
title = "Roughly 55 Cancri e @ fO2=IW-4"                   

[planet]
    tmp_surf        = 3000.0  
    instellation    = 3.3231e6
    albedo_b        = 0.0            
    s0_fact         = 0.6652         
    zenith_angle    = 60.0           
    albedo_s        = 0.0            
    radius          = 1.1959e7 
    gravity         = 22.304  
    tmp_int         = 0.0
    turb_coeff      = 0.001           
    wind_speed      = 2.0      
           
[files]
    input_sf        = "res/spectral_files/nogit/Dayspring/48/Dayspring.sf"   
    input_star      = "res/stellar_spectra/sun.txt"                       
    output_dir      = "out/"       
    fastchem_path   = "/Users/nichollsh/Projects/fastchem/"

[composition]
    p_top           = 1e-6     
    p_dict          = {H2O=1.435, CO2=0.11, N2=0.043, H2=499.004, CO=350.044, CH4=4.258,    SO2=0.01, FeO2=0.01}
    include_all     = true 
    chemistry       = 1                  
    condensates     = []               

[execution]
    clean_output    = true
    verbosity       = 1                  
    max_steps       = 20000              
    max_runtime     = 400                
    num_levels      = 42                 
    continua        = true               
    rayleigh        = false               
    cloud           = false              
    aerosol         = false              
    overlap_method  = 4                  
    thermo_funct    = true               
    sensible_heat   = true               
    latent_heat     = true               
    convection_type = "mlt"              
    solution_type   = 3                  
    solvers         = ["newton"]         
    dx_max          = 200.0              
    initial_state   = ["dry", "str", "2500"]     
    linesearch      = false              
    converge_atol   = 1.0e-2             
    converge_rtol   = 1.0e-3             

[plots]
    at_runtime      = true         
    temperature     = true         
    fluxes          = true         
    contribution    = true         
    emission        = true         
    albedo          = true         
    mixing_ratios   = true         
    animate         = true        

