# AGNI configuration file 
title = "Equilibrium chemistry demo"                    # Name for this configuration file

[planet]
    tmp_surf        = 2200.0            # Surface temperature [kelvin]
    instellation    = 44000.0          # Stellar flux at planet's orbital distance [W m-2]
    albedo_b        = 0.18              # Pseudo bond-albedo which removes downscales the stellar flux by 1-this_value
    s0_fact         = 0.375             # Stellar flux scale factor which accounts for planetary rotation (c.f. Cronin+13)
    zenith_angle    = 48.19             # Characteristic zenith angle for incoming stellar radiation [degrees]
    albedo_s        = 0.0               # Surface albedo
    radius          = 6.37e6            # Planet radius at the surface [m]
    gravity         = 9.81              # Gravitational acceleration at the surface [m s-2]
    p_surf          = 270.0             # Total surface pressure [bar]
    p_top           = 1e-5              # Total top-of-atmosphere pressure [bar]
    vmr             = { H2O = 0.6, CO2=0.1, N2=0.1, SO2=0.1, O2=0.05, Fe=0.05}     # Volatile volume mixing ratios
    tmp_eff         = 0.0               # Effective temperature

[files]
    clean_output    = true
    input_sf        = "res/spectral_files/Dayspring/48/Dayspring.sf"    # Path to SOCRATES spectral file.
    input_star      = "res/stellar_spectra/sun.txt"                     # Path to stellar spectrum scaled to 1 AU.
    output_dir      = "out/"                                            # Path to output directory.
    fastchem_path   = "/Users/nichollsh/Projects/fastchem/"

[execution]
    silent          = false                     # Disable all printing?
    max_steps       = 200                       # Maximum number of solver steps.
    max_runtime     = 400                       # Maximum wall-clock solver runtime [s].
    num_levels      = 40                        # Number of model levels.
    continua        = true                      # Include absorption from continua?
    rayleigh        = false                      # Include rayleigh scattering?
    cloud           = false                     # Include water cloud radiative properties?
    aerosol         = false                     # Include aerosol radiative properties?
    overlap_method  = 4                         # Method for treating line overlap.
    thermo_funct    = false                     # Use temperature-dependent thermodynamic properties?
    sensible_heat   = false                     # Include sensible heat transport at the surface?
    convection_type = "mlt"                     # Convection type ("" = no convection, "mlt" = use mixing length theory, "adj" = use convective adjustment).
    condensates     = []                        # List of volatiles which are allowed to condense.
    chemistry       = 1                         # Chemistry type (see wiki)
    solution_type   = 3                         # Solution type (see wiki).
    solvers         = ["newton"]                # Ordered list of solvers to apply (see wiki).
    initial_state   = ["iso","2000"]       # Ordered list of requests describing the initial state of the atmosphere (see wiki).
    wary            = false                     # Use various methods to help stabilise the model?
    converge_atol   = 1.0e-2                    # Convergence criterion on absolute flux lost [W m-2].
    converge_rtol   = 1.0e-4                    # Convergence criterion on relative flux lost [dimensionless].


[plots]
    at_runtime      = true                      # Make some plots at runtime?
    temperature     = true                      # Plot temperature profile?
    fluxes          = true                      # Plot fluxes?
    contribution    = true                      # Plot spectral contribution function?
    emission        = true                      # Plot emission spectrum?
    albedo          = true                      # Plot spectral albedo?
    mixing_ratios   = true                      # Plot mixing ratios?
    animate         = true                     # Make animation from runtime plots?

