# AGNI configuration file 
title = "Equilibrium chemistry demo"                    # Name for this configuration file

[planet]
    tmp_surf        = 2200.0    
    instellation    = 44000.0   
    albedo_b        = 0.18      
    s0_fact         = 0.375     
    zenith_angle    = 48.19     
    albedo_s        = 0.0       
    radius          = 6.37e6    
    gravity         = 9.81      
    p_surf          = 270.0     
    p_top           = 1e-5      
    vmr             = { H2O = 0.6, CO2=0.1, N2=0.1, SO2=0.1, O2=0.05, Fe=0.05, HO=0.0, H=0.0, CH4=0.0, CO=0.0, H2=0.0, SO=0.0, NH3=0.0, NH2=0.0, H2S=0.0, H2SO4=0.0}     # Volatile volume mixing ratios
    condensates     = []
    tmp_int         = 0.0    
[files]
    clean_output    = true
    input_sf        = "res/spectral_files/Dayspring/16/Dayspring.sf"    # Path to SOCRATES spectral file.
    input_star      = "res/stellar_spectra/sun.txt"                     # Path to stellar spectrum.
    output_dir      = "out/"                                            # Path to output directory.
    fastchem_path   = "/Users/nichollsh/Projects/fastchem/"

[execution]
    verbosity       = 1                        
    max_steps       = 200                      
    max_runtime     = 400                      
    num_levels      = 45                       
    continua        = true                     
    rayleigh        = false                    
    cloud           = false                    
    aerosol         = false                    
    overlap_method  = 4                        
    thermo_funct    = false                    
    sensible_heat   = false                    
    latent_heat     = false                    
    convection_type = "mlt"                    
    chemistry       = 1                        
    solution_type   = 3                        
    solvers         = ["newton"]               
    dx_max          = 200.0                    
    initial_state   = ["iso","2000"]           
    linesearch      = false                    
    converge_atol   = 1.0e-2                   
    converge_rtol   = 1.0e-4                   


[plots]
    at_runtime      = true                
    temperature     = true                
    fluxes          = true                
    contribution    = true                
    emission        = true                
    albedo          = true                
    mixing_ratios   = true                
    animate         = true                

