# AGNI configuration file 
title = "Test clouds w/ prescribed T(p)"                  

[planet]
    tmp_surf        = 1900.0       
    instellation    = 10000.0      
    albedo_b        = 0.0          
    s0_fact         = 0.375        
    zenith_angle    = 48.19        
    albedo_s        = 0.2          
    radius          = 6.37e6       
    gravity         = 9.81         
    p_surf          = 800.0        
    p_top           = 1e-6         
    vmr             = { H2O = 1.0 }
    condensates     = ["H2O"]
    tmp_eff         = 0.0          

[files]
    clean_output    = true
    input_sf        = "res/spectral_files/Frostflow/48/Frostflow.sf" 
    input_star      = "res/stellar_spectra/sun.txt"                  
    output_dir      = "out/"                                         

[execution]
    verbosity       = 1                     
    max_steps       = 200                   
    max_runtime     = 200                   
    num_levels      = 105                   
    continua        = true                  
    rayleigh        = false                 
    cloud           = true                  
    aerosol         = false                 
    overlap_method  = 4                     
    thermo_funct    = true                  
    sensible_heat   = false                 
    latent_heat     = false     
    convection_type = ""                    
    chemistry       = 0         
    solution_type   = 1                     
    solvers         = []                    
    dx_max          = 200.0                 
    initial_state   = ["dry","con","H2O"]   
    linesearch      = false                 
    converge_atol   = 5.0e-2                
    converge_rtol   = 1.0e-4                


[plots]
    at_runtime      = true       
    temperature     = true       
    fluxes          = true       
    contribution    = true       
    emission        = true       
    albedo          = true       
    mixing_ratios   = true       
    animate         = false      

