# AGNI configuration file 
title = "Condensation test"                    # Name for this configuration file

[planet]
    tmp_surf        = 2000.0          
    instellation    = 1300.0          
    albedo_b        = 0.0             
    s0_fact         = 0.375           
    zenith_angle    = 48.19           
    albedo_s        = 0.2             
    radius          = 6.37e6          
    gravity         = 9.81            
    p_surf          = 7000.0          
    p_top           = 1e-5            
    vmr             = { H2O=0.8, CO2=0.1, CH4=0.08, H2=0.02}    
    condensates     = ["H2O", "CO2"]
    tmp_int         = 0.0            
    turb_coeff      = 1.0e-4
    wind_speed      = 10.0
    skin_k          = 2.0
    skin_d          = 0.01
    tmp_magma       = 1700.0

[files]
    clean_output    = true
    input_sf        = "res/spectral_files/nogit/Dayspring/16/Dayspring.sf"  
    input_star      = "res/stellar_spectra/sun.txt"                         
    output_dir      = "out/"                                                

[execution]
    verbosity       = 1                
    max_steps       = 300              
    max_runtime     = 200              
    num_levels      = 40               
    continua        = true             
    rayleigh        = false            
    cloud           = false            
    aerosol         = false            
    overlap_method  = 4                
    thermo_funct    = true             
    sensible_heat   = true             
    latent_heat     = true             
    convection_type = "mlt"            
    chemistry       = 0             
    solution_type   = 1                
    solvers         = ["newton"]       
    dx_max          = 600.0            
    initial_state   = ["iso","2000"]   
    linesearch      = true             
    converge_atol   = 0.1              
    converge_rtol   = 1.0e-3           


[plots]
    at_runtime      = true         
    temperature     = true         
    fluxes          = true         
    contribution    = true         
    emission        = true         
    albedo          = true         
    mixing_ratios   = true         
    animate         = true         

