# AGNI configuration file
title = "Condensation test"

[planet]
    tmp_surf        = 1200.0
    instellation    = 2000.0
    albedo_b        = 0.0
    s0_fact         = 0.375
    zenith_angle    = 48.19
    surface_material= "greybody"
    albedo_s        = 0.2
    radius          = 6.37e6
    gravity         = 9.81
    flux_int        = 0.0
    turb_coeff      = 1.0e-4
    wind_speed      = 10.0
    skin_k          = 2.0
    skin_d          = 0.01
    tmp_magma       = 1700.0
    star_Teff       = 5000.0

[files]
    input_sf        = "res/spectral_files/Dayspring/48/Dayspring.sf"
    input_star      = "blackbody"
    output_dir      = "out/"

[composition]
    p_surf          = 7000.0
    p_top           = 1e-5
    vmr_dict        = { H2O=0.8, CO2=0.19, N2=0.01}
    chemistry       = 0
    condensates     = ["H2O"]

[execution]
    clean_output    = true
    verbosity       = 1
    max_steps       = 300
    max_runtime     = 400
    num_levels      = 44
    continua        = true
    rayleigh        = true
    cloud           = false
    overlap_method  = "ee"
    real_gas        = false
    thermo_funct    = true
    sensible_heat   = true
    latent_heat     = true
    convection      = true
    convection_crit = "l"
    rainout         = false
    solution_type   = 3
    solver          = "newton"
    dx_max          = 300.0
    initial_state   = ["loglin","800"]
    linesearch      = 1
    easy_start      = true
    converge_atol   = 1.0
    converge_rtol   = 1.0e-2
    perturb_all     = true


[plots]
    at_runtime      = true
    temperature     = true
    fluxes          = true
    contribution    = true
    emission        = true
    albedo          = true
    mixing_ratios   = true
    animate         = true
    height          = true
    cloud           = true
