# AGNI configuration file 
title = "Condensation test"                    # Name for this configuration file

[planet]
    tmp_surf        = 1700.0            # Surface temperature [kelvin]
    instellation    = 30.0          # Stellar flux at planet's orbital distance [W m-2]
    albedo_b        = 0.0              # Pseudo bond-albedo which removes downscales the stellar flux by 1-this_value
    s0_fact         = 0.375           # Stellar flux scale factor which accounts for planetary rotation (c.f. Cronin+13)
    zenith_angle    = 48.19             # Characteristic zenith angle for incoming stellar radiation [degrees]
    albedo_s        = 0.2               # Surface albedo
    radius          = 6.37e6            # Planet radius at the surface [m]
    gravity         = 9.81              # Gravitational acceleration at the surface [m s-2]
    p_surf          = 800.0             # Total surface pressure [bar]
    p_top           = 1e-5              # Total top-of-atmosphere pressure [bar]
    vmr             = { H2O=0.1, CO2=0.9, CH4=0.09, H2=0.01}     # Volatile volume mixing ratios
    condensates     = ["H2O","CO2"]
    tmp_eff         = 4.0               # Effective temperature
    turb_coeff      = 1.0e-4
    wind_speed      = 10.0

[files]
    clean_output    = true
    input_sf        = "res/spectral_files/Dayspring/16/Dayspring.sf"    # Path to SOCRATES spectral file.
    input_star      = "res/stellar_spectra/sun.txt"                     # Path to stellar spectrum scaled to 1 AU.
    output_dir      = "out/"                                            # Path to output directory.

[execution]
    silent          = false                     # Disable all printing?
    max_steps       = 300                       # Maximum number of solver steps.
    max_runtime     = 200                       # Maximum wall-clock solver runtime [s].
    num_levels      = 30                        # Number of model levels.
    continua        = true                      # Include absorption from continua?
    rayleigh        = false                     # Include rayleigh scattering?
    cloud           = false                     # Include water cloud radiative properties?
    aerosol         = false                     # Include aerosol radiative properties?
    overlap_method  = 4                         # Method for treating line overlap.
    thermo_funct    = false                     # Accounting temperature dependence of thermodynamic properties?
    sensible_heat   = true                     # Include sensible heat transport at the surface?
    latent_heat     = true                      # Include latent heat release?
    convection_type = "mlt"                        # Convection type ("" = no convection, "mlt" = use mixing length theory).
    chemistry       = 0
    solution_type   = 3                         # Solution type (see wiki).
    solvers         = ["newton"]                # Ordered list of solvers to apply (see wiki).
    dx_max          = 500.0                     # Maximum step size [Kelvin], when using nonlinear solvers
    initial_state   = ["iso","1000"]      # Ordered list of requests describing the initial state of the atmosphere (see wiki).
    linesearch      = true                      # Use linesearch?
    converge_atol   = 0.1                       # Convergence criterion on absolute flux divergence [W m-2].
    converge_rtol   = 1.0e-3                    # Convergence criterion on relative flux divergence [dimensionless].


[plots]
    at_runtime      = true                      # Make some plots at runtime?
    temperature     = true                      # Plot temperature profile?
    fluxes          = true                      # Plot fluxes?
    contribution    = true                      # Plot spectral contribution function?
    emission        = true                      # Plot emission spectrum?
    albedo          = true                      # Plot spectral albedo?
    mixing_ratios   = true                      # Plot mixing ratios?
    animate         = true                     # Make animation from runtime plots?

