# AGNI configuration file 
# This is designed to ROUGHLY approximate an equatorial Earth-like case
title = "Earth (ish)"                    # Name for this configuration file

[planet]
    tmp_surf        = 300.0             # Roughly 27 celcius
    instellation    = 1367.0            # Solar constant
    albedo_b        = 0.3               # From clouds
    s0_fact         = 0.375              
    zenith_angle    = 20.0              # Equatorial
    albedo_s        = 0.2               # Surface albedo
    radius          = 6.37e6            
    gravity         = 9.81              
    p_surf          = 1.0               
    p_top           = 1e-6              
    turb_coeff      = 0.001
    wind_speed      = 5.0

[files]
    clean_output    = true
    input_sf        = "res/spectral_files/Dayspring/48/Dayspring.sf"    # Path to SOCRATES spectral file.
    input_star      = "res/stellar_spectra/sun.txt"                     # Path to stellar spectrum scaled to 1 AU.
    input_vmr       = "doc/example_earth/equ.csv"       # RFM mixing ratios
    output_dir      = "out/"                                            # Path to output directory.

[execution]
    silent          = false                    
    max_steps       = 500                      
    max_runtime     = 400                      
    num_levels      = 70                       
    continua        = true                     
    rayleigh        = false                     
    cloud           = false                    
    aerosol         = false                    
    overlap_method  = 4                        
    thermo_funct    = false                    
    sensible_heat   = true                     
    convection_type = "adj"                     # dry adjustment
    condensates     = []         
    chemistry       = 0              
    solution_type   = 0                        
    solvers         = []              # timestepping works best in this case
    initial_state   = ["dry","str","100"]       # dry adiabat + stratosphere at 100 K
    stabilise       = true                     
    converge_atol   = 1.0e-9                   
    converge_rtol   = 1.0e-7                   

[plots]
    at_runtime      = true                      # Make some plots at runtime?
    temperature     = true                      # Plot temperature profile?
    fluxes          = true                      # Plot fluxes?
    contribution    = true                      # Plot spectral contribution function?
    emission        = true                      # Plot emission spectrum?
    albedo          = true                      # Plot spectral albedo?
    mixing_ratios   = true                      # Plot mixing ratios?
    animate         = true                     # Make animation from runtime plots?

