# AGNI configuration file
title = "Grey gas"

[planet]
    tmp_surf        = 2000.0
    instellation    = 90000.0
    albedo_b        = 0.18
    s0_fact         = 0.6652
    zenith_angle    = 60.0
    surface_material= "res/surface_albedos/lunarmarebasalt.dat"
    albedo_s        = 0.0
    radius          = 6.37e6
    mass            = 5.972e24
    flux_int        = 0.0
    turb_coeff      = 1.0e-2
    wind_speed      = 10.0
    star_Teff       = 5000.0

[files]
    input_sf        = "greygas"
    input_star      = "res/stellar_spectra/sun.txt"
    output_dir      = "out/"

[composition]
    p_surf          = 6000.0
    p_top           = 1e-5
    vmr_dict        = { H2 = 1.0}
    chemistry       = 0
    condensates     = []


[execution]
    clean_output    = true
    verbosity       = 1
    max_steps       = 200
    max_runtime     = 400
    num_levels      = 100
    continua        = true
    rayleigh        = false
    cloud           = false
    overlap_method  = "ee"
    real_gas        = true
    thermo_funct    = true
    sensible_heat   = false
    conduction      = false
    latent_heat     = false
    convection      = true
    convection_crit = "s"
    rainout         = false
    solution_type   = 3
    solver          = "newton"
    dx_max          = 500.0
    initial_state   = ["dry","str","50"]
    linesearch      = 0
    easy_start      = false
    converge_atol   = 1.0e-2
    converge_rtol   = 1.0e-4
    perturb_all     = false

[plots]
    at_runtime      = true
    temperature     = true
    fluxes          = true
    contribution    = false
    emission        = false
    albedo          = false
    mixing_ratios   = true
    animate         = true
    height          = true
    cloud           = false
