# AGNI configuration file 
# This is the default configuration file - it does not solve for RCE
title = "Default"                       # Name for this configuration file

[planet]
    tmp_surf        = 1000.0            # Surface temperature [kelvin]
    instellation    = 44000.0           # Stellar flux at planet's orbital distance [W m-2]
    albedo_b        = 0.18             # Pseudo bond-albedo which downscales the stellar flux by 1-this_value
    s0_fact         = 0.6652            # Stellar flux scale factor which accounts for planetary rotation (c.f. Cronin+13)
    zenith_angle    = 60.0              # Characteristic zenith angle for incoming stellar radiation [degrees]
    albedo_s        = 0.0               # Surface albedo
    radius          = 6.37e6            # Planet radius at the surface [m]
    gravity         = 9.81              # Gravitational acceleration at the surface [m s-2]
    p_surf          = 500.0             # Total surface pressure [bar]
    p_top           = 1e-5              # Total top-of-atmosphere pressure [bar]
    vmr             = { H2 = 1.0 }     # Volatile volume mixing ratios
    condensates     = []                # List of condensable gases

[files]
    clean_output    = true
    input_sf        = "res/spectral_files/Dayspring/256/Dayspring.sf"    # Path to SOCRATES spectral file.
    input_star      = "res/stellar_spectra/sun.txt"                     # Path to stellar spectrum.
    input_vmr       = ""                                                # Path to input volume mixing ratios. Not required if planet.vmr is passed.
    output_dir      = "out/"                                            # Path to output directory.

[execution]
    verbosity       = 1                         # Log level (0: none, 1: normal, 2: debug)
    max_steps       = 20000                     # Maximum number of solver steps.
    max_runtime     = 400                       # Maximum wall-clock solver runtime [s].
    num_levels      = 200                       # Number of model levels.
    continua        = true                      # Include absorption from continua?
    rayleigh        = false                      # Include rayleigh scattering?
    cloud           = false                     # Include water cloud radiative properties?
    aerosol         = false                     # Include aerosol radiative properties?
    overlap_method  = 4                         # Method for treating line overlap.
    thermo_funct    = false                     # Use temperature-dependent thermodynamic properties?
    sensible_heat   = false                     # Include sensible heat transport at the surface?
    latent_heat     = false                     # Include heat release from phase change
    convection_type = ""                        # Convection type (mlt = use mixing length theory).
    condensates     = []                        # List of volatiles which are allowed to condense.
    chemistry       = 0                         # Chemistry type (see wiki
    solution_type   = 0                         # Solution type (see wiki).
    solvers         = []                        # Ordered list of solvers to apply (see wiki).
    dx_max          = 200.0                     # Maximum step size [Kelvin], when using nonlinear solvers
    initial_state   = ["dry"]     # Ordered list of requests describing the initial state of the atmosphere (see wiki).
    linesearch      = false                     # Use linesearch?
    converge_atol   = 1.0e-3                    # Convergence criterion on absolute flux divergence [W m-2].
    converge_rtol   = 1.0e-1                    # Convergence criterion on relative flux divergence [dimensionless].

[plots]
    at_runtime      = true                      # Make some plots at runtime?
    temperature     = true                      # Plot temperature profile?
    fluxes          = true                      # Plot fluxes?
    contribution    = true                      # Plot spectral contribution function?
    emission        = true                      # Plot emission spectrum?
    albedo          = true                      # Plot spectral albedo?
    mixing_ratios   = true                      # Plot mixing ratios?
    animate         = false                     # Make animation from runtime plots?

