# AGNI configuration file
title = "K2-18 b, mixed"

[planet]
    tmp_surf        = 1000.0
    instellation    = 1368.0
    albedo_b        = 0.0
    s0_fact         = 0.375
    zenith_angle    = 48.19
    surface_material= "res/surface_albedos/lunarmarebasalt.dat"
    albedo_s        = 0.0
    radius          = 16628310.0
    gravity         = 12.43
    flux_int        = 0.0
    turb_coeff      = 1.0e-2
    wind_speed      = 10.0

[files]
    input_sf        = "res/spectral_files/Dayspring/256/Dayspring.sf"
    input_star      = "res/stellar_spectra/l-98-59.txt"
    output_dir      = "out/"

[composition]
    p_surf          = 10e3
    p_top           = 1e-5
    vmr_dict        = { H2O=0.424, H2=0.433, CO2=0.0715, CH4=0.0715 }
    vmr_file        = ""
    chemistry       = 0
    condensates     = ["H2O","CO2","CH4"]


[execution]
    clean_output    = true
    verbosity       = 1
    max_steps       = 200
    max_runtime     = 400
    num_levels      = 60
    continua        = true
    rayleigh        = true
    cloud           = false
    overlap_method  = "ee"
    real_gas        = true
    thermo_funct    = true
    sensible_heat   = true
    latent_heat     = false
    convection      = true
    rainout         = true
    solution_type   = 3
    solver          = "newton"
    dx_max          = 500.0
    initial_state   = ["loglin","500"]
    linesearch      = 2
    easy_start      = false
    converge_atol   = 1e-1
    converge_rtol   = 1.0e-3
    perturb_all     = true

[plots]
    at_runtime      = true
    temperature     = true
    fluxes          = true
    contribution    = true
    emission        = true
    albedo          = true
    mixing_ratios   = true
    animate         = false
    height          = false
