# AGNI configuration file
title = "L 98-59 d"

[planet]
    tmp_surf        = 2500.0
    instellation    = 6818.61
    albedo_b        = 0.0
    s0_fact         = 0.25
    zenith_angle    =  54.74
    surface_material= "res/surface_albedos/lunar_marebasalt.dat"
    albedo_s        = 0.0
    radius          = 8.091e6
    gravity         = 12.7
    flux_int        = 0.1
    turb_coeff      = 1.0e-2
    wind_speed      = 10.0

[files]
    input_sf        = "res/spectral_files/Honeyside/256/Honeyside.sf"
    input_star      = "res/stellar_spectra/l-98-59.txt"
    output_dir      = "out/"

[composition]
    p_surf          = 32.89e3
    p_top           = 1e-4
    vmr_dict        = { SO2=1.0 }
    vmr_file        = ""
    chemistry       = 0
    condensates     = []


[execution]
    clean_output    = true
    verbosity       = 1
    max_steps       = 200
    max_runtime     = 400
    num_levels      = 50
    continua        = true
    rayleigh        = true
    cloud           = false
    overlap_method  = "ee"
    real_gas        = true
    thermo_funct    = true
    sensible_heat   = true
    latent_heat     = true
    convection      = true
    rainout         = false
    solution_type   = 3
    solver          = "newton"
    dx_max          = 200.0
    initial_state   = ["loglin","600"]
    linesearch      = 0
    easy_start      = false
    converge_atol   = 1e-1
    converge_rtol   = 1.0e-3
    perturb_all     = true

[plots]
    at_runtime      = true
    temperature     = true
    fluxes          = true
    contribution    = true
    emission        = true
    albedo          = true
    mixing_ratios   = true
    animate         = false
    height          = false
    cloud           = false
