# AGNI configuration file
title = "Line-by-line validation tests"

[planet]
    tmp_surf        = 600.0
    instellation    = 0.0
    albedo_b        = 0.0
    s0_fact         = 1.0
    zenith_angle    = 0.0
    surface_material= "greybody"
    albedo_s        = 0.0
    radius          = 6.6e6
    gravity         = 20
    flux_int        = 0.0
    turb_coeff      = 0.0
    wind_speed      = 2.0

[files]
    input_sf        = "res/spectral_files/Mallard/318/Mallard.sf"
    input_star      = "res/stellar_spectra/sun.txt"
    # input_sf        = "out/ds4096.sf"
    # input_star      = ""
    output_dir      = "out/"

[composition]
    p_surf          = 123.0
    p_top           = 1e-6
    vmr_dict        = { H2O = 0.9, CO2=0.1 }
    chemistry       = 0
    condensates     = []

[execution]
    clean_output    = false
    verbosity       = 1
    max_steps       = 20000
    max_runtime     = 400
    num_levels      = 180
    continua        = false
    rayleigh        = false
    cloud           = false
    overlap_method  = "ro"
    real_gas        = false
    thermo_funct    = true
    sensible_heat   = false
    latent_heat     = false
    convection      = false
    rainout         = false
    solution_type   = 1
    solver          = ""
    dx_max          = 400.0
    initial_state   = ["dry", "sat", "H2O"]
    linesearch      = 0
    easy_start      = false
    converge_atol   = 1.0e-2
    converge_rtol   = 1.0e-3

[plots]
    at_runtime      = true
    temperature     = true
    fluxes          = true
    contribution    = true
    emission        = true
    albedo          = true
    mixing_ratios   = true
    animate         = false
    height          = true
