# AGNI configuration file
title = "ltt3780b_v5/case_00021"

[planet]
    tmp_surf        = 2700.0
    instellation    = 1.777080e+5
    albedo_b        = 0.0
    s0_fact         = 0.25
    zenith_angle    = 54.74
    surface_material= "blackbody"
    albedo_s        = 0.3
    radius          = 8.552843e+6
    gravity         = 1.275026e+1
    flux_int        = 0.0
    turb_coeff      = 0.001
    wind_speed      = 2.0
    skin_k          = 2.0
    skin_d          = 0.01
    tmp_magma       = 1724.947

[files]
    input_sf        = "res/spectral_files/Honeyside/256/Honeyside.sf"
    input_star      = "res/config/nogit_mnras.sflux"
    output_dir      = "out/"

[composition]
    p_top           = 1e-5
    p_dict          = {H2O = 648.09,CO2 = 498.27,H2  = 2.40  ,CH4 = 0.00  ,CO  = 6.51  ,N2  = 3.84  ,S2  = 73.69 ,SO2 = 223.93}
    include_all     = true
    chemistry       = 1
    condensates     = []

[execution]
    clean_output    = true
    verbosity       = 1
    max_steps       = 20000
    max_runtime     = 400
    num_levels      = 60
    continua        = true
    rayleigh        = true
    cloud           = false
    aerosol         = false
    overlap_method  = 4
    thermo_funct    = true
    gravity_funct   = true
    sensible_heat   = true
    latent_heat     = true
    convection      = true
    solution_type   = 2
    solvers         = ["newton"]
    dx_max          = 400.0
    initial_state   = ["loglin", "700"]
    linesearch      = 0
    easy_start      = false
    converge_atol   = 1.0e-2
    converge_rtol   = 1.0e-3

[plots]
    at_runtime      = true
    temperature     = true
    fluxes          = true
    contribution    = true
    emission        = true
    albedo          = true
    mixing_ratios   = true
    animate         = true
    height          = true
