# AGNI configuration file used when coupling to PROTEUS
title = "PROTEUS configured"

[planet]
    p_top           = 1e-05
    tmp_surf        = 1000
    instellation    = 800.0
    s0_fact         = 0.375
    albedo_b        = 0.3
    zenith_angle    = 48.19
    albedo_s        = 0.3
    gravity         = 9.819943999997438
    radius          = 6371000.0
    p_surf          = 973.000
    skin_k          = 2.0
    skin_d          = 0.01
    tmp_magma       = 2009.1074604027003
    # tmp_eff         = 1000.0

[planet.vmr]
    H2O = 0.7
    CO2 = 0.2
    H2 = 0.0
    N2 = 0.0
    CH4 = 0.0
    CO = 0.1

[files]
    clean_output    = true
    output_dir      = "out/"
    input_sf        = "res/spectral_files/Dayspring/16/Dayspring.sf"
    input_star      = "res/stellar_spectra/sun.txt" 

[execution]
    silent          = false  
    max_steps       = 2000
    max_runtime     = 400    
    continua        = true   
    aerosol         = false  
    overlap_method  = 4      
    thermo_funct    = false  
    sensible_heat   = false  

    convection_type = "mlt" 
    condensates     = [] 
    solvers         = ["newton"]    
    dx_max          = 200.0                   
    chemistry       = 0
    initial_state   = ["dry","str","400"] 
    wary            = false   
    converge_atol   = 1.0e-2  
    converge_rtol   = 2.0e-3  
    num_levels = 40
    rayleigh = true
    cloud = false
    solution_type = 2

[plots]
    animate         = false
    at_runtime = true
    temperature = true
    fluxes = true
    contribution = true
    emission = true
    albedo = true
    mixing_ratios = true
