# AGNI configuration file 
title = "Comparison with Selsis+23"  

[planet]
    tmp_surf        = 2000.0         
    instellation    = 40000          
    albedo_b        = 0.0            
    s0_fact         = 0.375          
    zenith_angle    = 48.19          
    albedo_s        = 0.0            
    radius          = 6.37e6         
    gravity         = 9.81           
    p_surf          = 270.0          
    p_top           = 1e-5           
    vmr             = { H2O = 1.0 }  
    condensates     = ["H2O"]        
    tmp_eff         = 0.0            
    turb_coeff      = 1.0e-4
    wind_speed      = 10.0

[files]
    clean_output    = true
    input_sf        = "res/spectral_files/Frostflow/256/Frostflow.sf"   
    input_star      = "res/stellar_spectra/sun.txt"                     
    output_dir      = "out/"                                            

[execution]
    verbosity       = 1             
    max_steps       = 200           
    max_runtime     = 400           
    num_levels      = 40            
    continua        = true          
    rayleigh        = true          
    cloud           = false         
    aerosol         = false         
    overlap_method  = 4             
    thermo_funct    = false         
    sensible_heat   = true          
    latent_heat     = true          
    convection_type = "mlt"         
    condensates     = []            
    chemistry       = 0            
    solution_type   = 3             
    solvers         = ["newton"]    
    dx_max          = 400.0         
    initial_state   = ["ncdf","nogit_debug/selsis_ff/40/atm.nc"]    
    linesearch      = false                                         
    converge_atol   = 1.0e-2                                        
    converge_rtol   = 1.0e-4                                        


[plots]
    at_runtime      = true         
    temperature     = true         
    fluxes          = true         
    contribution    = true         
    emission        = true         
    albedo          = true         
    mixing_ratios   = true         
    animate         = true         

