# AGNI configuration file
title = "TOI-561 b, pure CO2"

[planet]
    tmp_surf        = 2000.0
    instellation    = 6.569e6 # from SMA of Polanski+24
    albedo_b        = 0.0
    s0_fact         = 1.0
    zenith_angle    = 0.0
    surface_material= "res/surface_albedos/lunar_marebasalt.dat"
    albedo_s        = 0.0
    radius          = 9.287e6
    gravity         = 13.9 # Polanski+24
    flux_int        = 0.0
    turb_coeff      = 1.0e-2
    wind_speed      = 10.0

[files]
    input_sf        = "res/spectral_files/Dayspring/256/Dayspring.sf"
    input_star      = "res/stellar_spectra/sun.txt"
    output_dir      = "out/"

[composition]
    p_surf          = 1e2
    p_top           = 1e-4
    vmr_dict        = { CO2 = 1.0}
    vmr_path        = ""
    include_all     = false
    chemistry       = 0
    condensates     = []


[execution]
    clean_output    = true
    verbosity       = 1
    max_steps       = 200
    max_runtime     = 400
    num_levels      = 35
    continua        = true
    rayleigh        = true
    cloud           = false
    aerosol         = false
    overlap_method  = "ee"
    thermo_funct    = true
    gravity_funct   = true
    sensible_heat   = true
    latent_heat     = false
    convection      = true
    rainout         = false
    solution_type   = 3
    solvers         = ["newton"]
    dx_max          = 400.0
    initial_state   = ["iso","2300"]
    linesearch      = 2
    easy_start      = false
    converge_atol   = 1.0e-2
    converge_rtol   = 1.0e-3


[plots]
    at_runtime      = true
    temperature     = true
    fluxes          = true
    contribution    = true
    emission        = true
    albedo          = true
    mixing_ratios   = true
    animate         = true
    height          = true
