#! /bin/sh
#
#   Script to calculate shortwave fluxes and radiances.
#
#   Make Solar Fields
#
$RAD_SCRIPT/Cgen_horiz_cdl -o $RAD_DIR/examples/aer_cmp/laer27.stoa \
                           -n stoa -L "Solar Irradiance" -u "W.m-2" \
                           -F 1365.0 -N 0.0 -T 0.0

$RAD_SCRIPT/Cgen_horiz_cdl -o $RAD_DIR/examples/aer_cmp/laer27.szen \
                           -n szen -L "Solar zenith angle" -u "Degrees" \
		           -F 0.0 -N 0.0 -T 0.0

$RAD_SCRIPT/Cgen_horiz_cdl -o $RAD_DIR/examples/aer_cmp/laer27.sazim \
                           -n sazim -L "Solar azimuthal angle" \
                           -u "Degrees" -F 0.0 -N 0.0 -T 0.0
			   
$RAD_SCRIPT/Cgen_view_cdl -o $RAD_DIR/examples/aer_cmp/laer27.view  \
                          -p 30.0 -a 0.0 -v 0.0 -N 0.0 -T 0.0

$RAD_SCRIPT/Cmid_point -o $RAD_DIR/examples/aer_cmp/laer27.mid \
                          $RAD_DIR/examples/aer_cmp/laer27.tl

$RAD_SCRIPT/Cscale_field -R 0.0,1.2e5:0.0 -o $RAD_DIR/examples/aer_cmp/laer27.null \
                         -n "nul" -u "None" \
                         -L "Null Field" $RAD_DIR/examples/aer_cmp/laer27.mid

$RAD_SCRIPT/Cinc_field -R 1.0e4,2.0e4:1.0 -o $RAD_DIR/examples/aer_cmp/laer27.clfr \
	               -n "clfr" -u "None" \
		       -L "Cloud Fraction" $RAD_DIR/examples/aer_cmp/laer27.null

$RAD_SCRIPT/Cinc_field -R 0.0,1.2e5:0.000025 -o $RAD_DIR/examples/aer_cmp/laer27.iwm  \
                       -n "iwm" -u "kg/kg" \
                       -L "Ice Water Content" $RAD_DIR/examples/aer_cmp/laer27.null

$RAD_SCRIPT/Cinc_field -R 0.0,1.2e5:0.000010 -o $RAD_DIR/examples/aer_cmp/laer27.ire \
                       -n "dl" -u "m" \
	               -L "Mean maximum dimension" $RAD_DIR/examples/aer_cmp/laer27.null

$RAD_SCRIPT/Cl_run_cdl \
          -s $RAD_DIR/data/spectra/hadgem1/sp_sw_hadgem1_3 \
	  -R 1 6 \
          -B $RAD_DIR/examples/aer_cmp/laer27 \
	  -C 5 -G 5 0 \
	  -g 2 -K 1 -r +R \
	  -S -t 16 -v 13 -x zz1 
