#! /bin/ksh
#
# SCRIPT TO RUN PROCESSING PROGRAM FOR RAW INPUT
#
touch $LOCK_FILE
set -- `getopt B:m: $*`
while [ "$1" != "--" ]
do case $1 in
      -B) base_name=$2 ;;
      -m) missing_data=$2 ;;
      -*) echo "Incorrect usage."; exit -1 ;;
   esac
   shift 2
done
shift
cat > /tmp/ri.$$ << EOF
$1
$base_name
EOF
if [ "$missing_data" ] 
   then cat >> /tmp/ri.$$ << EOF
y
$missing_data
EOF
else
   echo n >> /tmp/ri.$$
fi
raw_input < /tmp/ri.$$ > /dev/null
rm -f /tmp/ri.$$
rm -f $LOCK_FILE
