#! /bin/ksh
#
# Script to find string in all .f files.
#
cd $RAD_BIN
LIST=" "
INCLIST=" "
for IFILE in *.finc
do
   if  [ $(grep -n $1 $IFILE | wc | cut -f 1 -d " ") -gt 0 ]
      then INCLIST=${INCLIST}" "$IFILE
   fi
done
for FILE in *.f
do 
   if  [ $(grep -n $1 $FILE | wc | cut -f 1 -d " ") -gt 0 ] 
      then LIST=${LIST}" "$FILE
   fi
   if [ "$INCLIST" != " " ]
      then for IFILE in "$INCLIST"
      do 
         if  [ $(grep -n $1 $IFILE | wc | cut -f 1 -d " ") -gt 0 ]
            then if  [ $(grep -n $IFILE $FILE | wc | cut -f 1 -d " ") -gt 0 ]
               then LIST=${LIST}" "$FILE
            fi
         fi
      done
   fi
done
touch $LIST

