# AGNI configuration file
title = "Grey gas with thermal conduction"

[planet]
    tmp_surf        = 2000.0
    instellation    = 1e6
    albedo_b        = 0.0
    s0_fact         = 1.0
    zenith_angle    = 0.0
    surface_material= "greybody"
    albedo_s        = 0.0
    radius          = 8064561.9164
    mass            = 9.79e24
    flux_int        = 0.0
    roughness       = 1.0e-2
    wind_speed      = 10.0
    star_Teff       = 4000.0

[files]
    input_sf        = "greygas"
    input_star      = "blackbody"
    output_dir      = "out/"

[composition]
    p_surf          = 1e1
    p_top           = 1e-15
    vmr_dict        = { H2 = 1.0, H2O=1e-4}
    condensates     = []


[execution]
    clean_output    = true
    verbosity       = 1
    max_steps       = 200
    max_runtime     = 400
    num_levels      = 80
    solution_type   = 1
    solver          = "newton"
    dx_max          = 400.0
    initial_state   = ["loglin","2200"]
    linesearch      = 2
    easy_start      = false
    grey_start      = false
    converge_atol   = 1.0e-2
    converge_rtol   = 1.0e-4
    perturb_all     = true

[physics]
    chemistry       = false
    continua        = true
    rayleigh        = false
    cloud           = false
    overlap_method  = "ee"
    grey_lw         = 1e-3
    grey_sw         = 1e-2
    real_gas        = true
    thermo_funct    = true
    sensible_heat   = true
    conduction      = true
    latent_heat     = false
    convection      = true
    convection_crit = "s"
    rainout         = false
    oceans          = false

[plots]
    at_runtime      = true
    temperature     = true
    fluxes          = true
    contribution    = false
    emission        = false
    albedo          = false
    mixing_ratios   = true
    animate         = true
    height          = true
    cloud           = false
