# This job installs and builds AGNI
# This occurs when a PR to main is created

name: Install and build AGNI

on:
  pull_request:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest
    name: Install and build
    steps:
      - uses: actions/checkout@v4

      - name: NetCDF
        run: |
          sudo apt update 
          sudo apt-get install libnetcdff-dev netcdf-bin gfortran gcc

      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.10'

      - name: SOCRATES
        run: |
          export LD_LIBRARY_PATH=""
          cd socrates
          ./configure
          ./build_code 
          source set_rad_env 
          
    
